use aes::Aes256;
use anyhow::{anyhow, Context, Result};
use base64::engine::general_purpose::STANDARD as B64;
use base64::Engine as _;
use cbc::cipher::{block_padding::Pkcs7, BlockDecryptMut, KeyIvInit};
use serde::Deserialize;

type Aes256CbcDec = cbc::Decryptor<Aes256>;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ConnectionKind {
    Vnc,
    Rdp,
    Ssh,
}

impl ConnectionKind {
    #[allow(dead_code)] // wired up in T1C.3 (guacd handshake)
    pub fn protocol_name(self) -> &'static str {
        match self {
            ConnectionKind::Vnc => "vnc",
            ConnectionKind::Rdp => "rdp",
            ConnectionKind::Ssh => "ssh",
        }
    }
}

/// Connection details consumed by guacd. Mirrors the legacy Python at
/// flowcase/routes/droplet.py:578-616 (the orchestrator-side encoder).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GuacConnection {
    pub kind: ConnectionKind,
    pub hostname: String,
    pub port: u16,
    pub username: Option<String>,
    pub password: Option<String>,
}

#[derive(Debug, Deserialize)]
struct Envelope {
    iv: String,
    value: String,
}

#[derive(Debug, Deserialize)]
struct InnerToken {
    connection: ConnectionPayload,
}

#[derive(Debug, Deserialize)]
struct ConnectionPayload {
    #[serde(rename = "type")]
    kind: String,
    settings: SettingsPayload,
}

#[derive(Debug, Deserialize)]
struct SettingsPayload {
    hostname: String,
    /// Port may arrive as either a JSON number or a JSON string in the
    /// orchestrator's payload — accept both shapes.
    #[serde(deserialize_with = "deserialize_port")]
    port: u16,
    username: Option<String>,
    password: Option<String>,
    // disable-copy, disable-paste, etc. are intentionally ignored — guacd
    // gets them from us during the handshake (T1C.3) based on policy.
}

fn deserialize_port<'de, D: serde::Deserializer<'de>>(d: D) -> Result<u16, D::Error> {
    use serde::de::Error as _;
    let v = serde_json::Value::deserialize(d)?;
    match v {
        serde_json::Value::Number(n) => n
            .as_u64()
            .filter(|p| *p <= u16::MAX as u64)
            .map(|p| p as u16)
            .ok_or_else(|| D::Error::custom("port out of u16 range")),
        serde_json::Value::String(s) => s
            .parse::<u16>()
            .map_err(|e| D::Error::custom(format!("port not a u16: {e}"))),
        other => Err(D::Error::custom(format!(
            "port must be a number or string, got {other}"
        ))),
    }
}

/// Decrypt a token issued by the orchestrator.
///
/// Format (from flowcase/routes/droplet.py:595-614):
///
/// ```text
/// b64_token = b64( json({"iv": b64(16-byte IV), "value": b64(AES-256-CBC(pkcs7(json(connection))))}) )
/// ```
#[allow(dead_code)] // wired up in T1C.4
pub fn decrypt_token(b64_token: &str, key: &[u8; 32]) -> Result<GuacConnection> {
    let envelope_bytes = B64
        .decode(b64_token.trim())
        .context("base64 decoding outer token")?;
    let envelope: Envelope =
        serde_json::from_slice(&envelope_bytes).context("parsing token envelope JSON")?;

    let iv = B64
        .decode(envelope.iv.as_bytes())
        .context("base64 decoding IV")?;
    if iv.len() != 16 {
        return Err(anyhow!("IV must be 16 bytes, got {}", iv.len()));
    }
    let mut iv_arr = [0u8; 16];
    iv_arr.copy_from_slice(&iv);

    let ciphertext = B64
        .decode(envelope.value.as_bytes())
        .context("base64 decoding ciphertext")?;

    let plaintext = Aes256CbcDec::new(key.into(), &iv_arr.into())
        .decrypt_padded_vec_mut::<Pkcs7>(&ciphertext)
        .map_err(|e| anyhow!("AES-256-CBC decrypt failed: {e}"))?;

    let inner: InnerToken =
        serde_json::from_slice(&plaintext).context("parsing decrypted connection JSON")?;

    let kind = match inner.connection.kind.as_str() {
        "vnc" => ConnectionKind::Vnc,
        "rdp" => ConnectionKind::Rdp,
        "ssh" => ConnectionKind::Ssh,
        other => return Err(anyhow!("unsupported connection type: {other}")),
    };

    Ok(GuacConnection {
        kind,
        hostname: inner.connection.settings.hostname,
        port: inner.connection.settings.port,
        username: inner.connection.settings.username,
        password: inner.connection.settings.password,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Fixture generated by:
    ///
    /// ```js
    /// const crypto = require('crypto');
    /// const key = Buffer.from('this-is-a-32-byte-test-key!12345');
    /// const iv = Buffer.from('AAAAAAAAAAAAAAAA');
    /// const inner = { connection: { type: 'vnc', settings: {
    ///     hostname: '10.0.0.42', username: 'kasm_user',
    ///     password: 'secretsecret', port: 5901,
    ///     'disable-copy': 'false', 'disable-paste': 'false' } } };
    /// const c = crypto.createCipheriv('aes-256-cbc', key, iv);
    /// const enc = Buffer.concat([c.update(JSON.stringify(inner), 'utf8'), c.final()]);
    /// const env = { iv: iv.toString('base64'), value: enc.toString('base64') };
    /// console.log(Buffer.from(JSON.stringify(env)).toString('base64'));
    /// ```
    const KEY: &[u8; 32] = b"this-is-a-32-byte-test-key!12345";
    const TOKEN: &str = "eyJpdiI6IlFVRkJRVUZCUVVGQlFVRkJRVUZCUVE9PSIsInZhbHVlIjoiUGd0ZXJ3SmREdE9MenhBSWlpeGM3UUxHTm1VbEsxVHVZWG1PZ09PY3NkbUoxam9JcGVtNnVCbVdKdTlNR3VTZ0grajBYRDk5akdFWm9UNGd3Z2RGMTVtWkQ3bjZxamJlTWY4UnJ5dUNKQUxvaFZLSFpod25HaHBxelVqRFdCRHdFSk5IOWpBcktESnp2L0RMY29BczJ2WUpsenluaE16bXUzR3hQb3Q2YnY1VHJlK05COEd2Wm5tUUlyVnRUZ0M5SjRiZ0xsRXEzb3E4RFFKczNPTFgvaFd1WWs4RE85WWMycDJvZUtBbkd2ND0ifQ==";

    #[test]
    fn decrypts_known_node_fixture() {
        let conn = decrypt_token(TOKEN, KEY).expect("decrypt should succeed");
        assert_eq!(conn.kind, ConnectionKind::Vnc);
        assert_eq!(conn.hostname, "10.0.0.42");
        assert_eq!(conn.port, 5901);
        assert_eq!(conn.username.as_deref(), Some("kasm_user"));
        assert_eq!(conn.password.as_deref(), Some("secretsecret"));
    }

    #[test]
    fn rejects_wrong_key() {
        let mut bad = *KEY;
        bad[0] ^= 0x01;
        let result = decrypt_token(TOKEN, &bad);
        assert!(result.is_err(), "wrong key should fail decryption");
    }

    #[test]
    fn rejects_garbage_outer_base64() {
        let result = decrypt_token("!!!not-base64!!!", KEY);
        assert!(result.is_err());
    }

    #[test]
    fn rejects_wrong_size_iv() {
        // Build an envelope with a 4-byte IV instead of 16.
        let envelope = serde_json::json!({
            "iv": B64.encode([0u8; 4]),
            "value": B64.encode([0u8; 16]),
        });
        let token = B64.encode(serde_json::to_vec(&envelope).unwrap());
        let result = decrypt_token(&token, KEY);
        assert!(result.is_err());
    }

    #[test]
    fn protocol_name_matches_guacd_keys() {
        assert_eq!(ConnectionKind::Vnc.protocol_name(), "vnc");
        assert_eq!(ConnectionKind::Rdp.protocol_name(), "rdp");
        assert_eq!(ConnectionKind::Ssh.protocol_name(), "ssh");
    }
}
